Refreshed DNS at Sat May 23 00:00:11 PDT 2020

Start monitoring after 0 seconds ...
1: May 23 00:00:11 2020
ALERT!! [2020-05-22 14:58:43] https://www.youtube.com/watch?v=Rmf6T_Ewt38)
[2020-05-22 16:42:42] https://hangouts.google.com/)
ALERT!! [2020-05-22 16:44:04] https://www.youtube.com/watch?v=H1WBdh56Vq4)
ALERT!! [2020-05-22 16:58:40] https://www.youtube.com/watch?v=PdBeBQMnN6I)
ALERT!! [2020-05-22 17:23:44] https://www.youtube.com/)
ALERT!! [2020-05-22 17:24:04] https://www.youtube.com/watch?v=f-iP28NP6X8)
ALERT!! [2020-05-22 20:02:00] https://shellshock.io/)
ALERT!! [2020-05-22 20:47:14] https://shellshock.io/?equip=inventory)
[2020-05-22 21:41:38] https://www.google.com/search?q=cum&oq=cum&aqs=chrome..69i57j0l2j46j0l2j46j69i61.824j0j1&sourceid=chrome&ie=UTF-8)
[2020-05-22 21:41:43] https://www.google.com/search?q=cum&safe=strict&sxsrf=ALeKk03hpAzJWPSC8KFKZTbVmN3I9wroUQ:1590208896504&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiQ6pPjlcnpAhVLqp4KHZzGDpkQ_AUoAnoECAwQBA&biw=1920&bih=969&dpr=1)
ALERT!! [2020-05-22 21:45:29] https://shellshock.io/?home)
ALERT!! [2020-05-22 21:45:50] https://shellshock.io/?loadingAd=true)
ALERT!! [2020-05-22 21:54:09] https://shellshock.io/?game=menu)
ALERT!! [2020-05-22 21:54:16] https://shellshock.io/?game=play)
[2020-05-23 00:00:00] https://calendar.google.com/calendar/b/1/r/week)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abutala/bin/BrowserAlert/alert_me.py", line 108, in <module>
    raise(e)
  File "/home/abutala/bin/BrowserAlert/alert_me.py", line 105, in <module>
    (alert, msg, matched) = run_monitor_one_shot(args.ignore_patterns)
  File "/home/abutala/bin/BrowserAlert/alert_me.py", line 38, in run_monitor_one_shot
    msg2 = NetHelpers.ssh_cmd_v2(Constants.GARMOUGAL_IP, Constants.GARMOUGAL_USERNAME, Constants.GARMOUGAL_PASSWORD, remote_cmd)
  File "/home/abutala/bin/lib/NetHelpers.py", line 42, in ssh_cmd_v2
    client.connect(node, username=user, password=passwd, timeout=10)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
